name: Docker Conditional CI

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Docker version
        run: docker --version

      - name: Build Docker image
        id: build
        run: |
          docker build \
            -t github-actions-practice:${{ github.sha }} .

      - name: Show success message
        if: success()
        run: echo "Docker image built successfully!"

      - name: Show failure message
        if: failure()
        run: echo "Docker build failed!"

      - name: Show final message
        if: always()
        run: echo "Docker workflow finished."
