name: My First GitHub Action

on:
  push:
    branches:
      - main

jobs:
  practice:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello
        run: echo "Hello from GitHub Actions!"

      - name: Check Runner
        run: |
          echo "I am running inside GitHub!"
          uname -a
        
